name: extension - test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/extension/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/extension/**'
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Design system install dependencies
        run: |-
          cd packages/design
          yarn --ignore-engines
      - name: Design system build
        run: |-
          cd packages/design
          yarn build
      - name: Install dependencies
        run: |-
          cd apps/extension
          yarn --ignore-engines
      - name: Run build
        run: |-
          cd apps/extension
          yarn build
      - name: Install Playwright Browsers
        run: npx playwright@1.22.1 install-deps chromium
      - name: Run Playwright tests
        run: |-
          cd apps/extension
          xvfb-run --auto-servernum -- yarn test
