name: website - test
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/website/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/website/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Files
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.0
      - name: Print Node version
        run: node -v
      - name: Print yarn version
        run: yarn -v
      - name: Run design system build
        run: |-
          cd packages/design-system
          yarn build
      - name: Install dependencies
        run: |-
          cd apps/website
          yarn --ignore-engines
      - name: Run build
        run: |-
          cd apps/website
          yarn build
